openapi: '3.1'
info:
  title: 'Pokemon API'
  summary: 'Pokemon REST API as technical assessment for Annalect'
  version: '0.1'
paths:
  
components:
  schemas:
    Pokemon:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        primary_type:
          type: string
        secondary_type:
          type: string
        total:
          type: integer
          format: int32
        hp:
          type: integer
          format: int32
        attack:
          type: integer
          format: int32
        defense:
          type: integer
          format: int32
        special_attack:
          type: integer
          format: int32
        special_defense:
          type: integer
          format: int32
        speed:
          type: integer
          format: int32