# Generated by Django 4.1.6 on 2023-02-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='generation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='legendary',
            field=models.BooleanField(default=False),
        ),
    ]
